---
title: "Valery Zúñiga Kondrashov"
date: "`r Sys.Date()`"
author: 
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

#### Escazú, Costa Rica ⬝ (+506) 8439-4445 ⬝ telaroz@gmail.com ⬝ https://github.com/telaroz/ ⬝ https://twitter.com/telaroz/ ⬝ https:/telaroz.com

## Educación

**Data ScienceTech Institute**, (2020 - Presente).    
Maestría Aplicada, Ciencia de Datos e Inteligencia Artificial

**Universidad de Costa Rica, Escuela de Matemática** (2013 - 2018).  
Bachillerato, Ciencias Actuariales


## Experiencia 

**Mastercard SJO Center of Excellence**  
Associate Consultant, Advanced Analytics.  
San José, Costa Rica. Mayo 2019 -- Presente

* Desarrollo y entrega de sofisticados productos de análisis de datos para gran variedad de entidades financieras de todo el continente, apoyados en los cientos de GB de data transaccional que sostiene la compañía. Las entregas abarcan segmentaciones comportamentales de clientes, análisis post hoc de desempeño de campañas, modelos de migración de productos, diagnósticos de autorizaciones y fraudes, asesoramientos de calidad de data, entre otros esfuerzos menores.
* Presentaciones técnicas y metodológicas de los proyectos, para stakeholders internos como externos, de perfiles mayoritariamente no técnicos.
* Desarrollo de paquetes de R propietarios para uso interno. Estos paquetes permiten llevar a cabo proyectos de principio a fin de forma más sencilla y automatizada, además de recopilar funciones que pueden ser utilizadas para múltiples propósitos.
* Capacitaciones internas de R al propio equipo.

**Instituto Nacional de Seguros**  
Técnico en Reservas  
San José, Costa Rica. Enero 2018 – Abril 2019

* Reescritura y automatización desde VBA y Excel hacia R del cálculo de las reservas por seguros.
*	Uso de métodos estadístisticos para proyectar reservas y simulación de múltiples escenarios.

**Centro de Investigación en Matemática Pura y Aplicada (CIMPA)**  
Asistente de Investigación - Estudio de tránsito en la Gran Área Metropolitana (Dr. Maikol Solís)
San José, Costa Rica. Marzo 2017 – Enero 2018

* Manipulación de datos de conexiones celulares a antenas
*	Estudio y graficación del movimiento de los individuos

## Experiencia Académica



**Clasificación de sentimientos en textos cortos e informales en español**
 
Procesamiento de Lenguaje Natural  
Desarrollado en R, Ago 2016 - Jul 2017

- Construcción matemática rigurosa de una medida signada para apalancar una herramienta de clasificación de texto para cualquier dicotomía de sentimientos.

**Análisis del mercado de flores a través de tendencias de búsquedas en Google**  
Análisis de series de tiempo  
Desarrollado en R, Nov 2017 - Dic 2017

- Utilizando modelos básicos de análisis de series de tiempo como modelos ARIMA, se caracterizaron las fluctuaciones y crecimiento esperado del mercado de flores basándonos en la serie de tiempo de búsquedas de la palabra 'flower'.


**Estrategias de apuestas en línea sobre partidos de la MLB**  
Backtesting  
Desarrollado en VBA, Jun 2016 - Jul 2016


- Simulamos el desempeño de distintas estrategias de apuestas que podría jugar un individuo sin conocimiento del deporte, basándose solamente en información extraída de páginas de apuestas en línea. Desarrollamos una estrategia de Martingala modificada con buenas probabilidades de ganancias en cualquier subconjunto del periodo estudiado.

## Experiencia Extracurricular

**ConectaR, 2019**  
San José, Costa Rica  
Enero 2019 

* **Charla Plenaria:** "¿Cómo migrar de Excel a R? Un ejercicio práctico de aplicación en la industria."
   Traductor automático de código VBA a R.
   Automatización en R de procesos desde la lectura de datos en Excel, manipulación y escritura en Excel.
  
* **Poster:** "Comparación de métodos de clasificación con R"

**Selección Nacional de Balonmano de Costa Rica**  
Marzo 2014 - Actualidad

- Juegos Centroamericanos y del Caribe 2018

- Torneo Centroamericano Masculino Mayor El Salvador 2019 - Oro


## Habilidades técnicas

  - Dominio avanzado de desarrollo en R: creación de paquetes, paralelización y alta eficiencia
  - Conocimiento en visualización de datos: Uso de ggplot2
  - Habilidades en desarrollo de aplicaciones Shiny
  - Conocimiento sólido en Excel y VBA
  - Conocimiento sólido en Matlab
  - Creación de modelos de Deep Learning con Tensorflow a través de Keras en R
  - Uso de Impala y Spark a través de R, apalancado del conocimiento en SQL
  - Conocimiento básico de Python


## Idiomas

- Español: Nativo
- Ruso: Fluido Conversacional 
- Inglés: Dominio a nivel técnico y de negocios.
- Alemán: Dominio avanzado (C1). Abitur completado en alemán
- Francés: Nivel básico (A1)

